name: Code Quality

on:
  push:
    branches: [ preprod, prod ]
  pull_request:

jobs:
  quality:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - run: npm ci

      - uses: biomejs/setup-biome@v2

      - name: Run Biome (Lint, Format, Check)
        run: biome ci .

      - name: Type Check
        run: npx tsc --noEmit

      - name: Build Check (dry run)
        run: npx vite build --mode production

      - name: Audit Dependencies
        run: npm audit --audit-level=moderate
